yolo_model:

  config_file:
    name: yolov3-tiny.cfg
  weight_file:
    name: yolov3-tiny_last.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - friend
      - enemy
      - IFF